### ISSUE TITLE
For Organism Header vertical scrolling should be optional.

### ISSUE THREAD

**Issue by ralden** [ioet/ioet-website-v2#33]
Right now if a page with a Header at the top scrolls vertically the header scrolls too. Probably for both the header and the footer this should be optional. I would like to make the header "freeze" at the top and have everything else scroll.

I do not foresee the footer needing to freeze but I assume if you can make this work for the header you can do it for the footer too and it would be silly not to have the same control for both.

**Comment by Wason1797** [comment]
We are going to enable the position property override on that component.
